Migrate to modern stack, including TS, new linting, updated APIs
lokesh/color-thief pull request #255
Opened 2024-06-28 09:03 UTC by simplePCBuilding

# What's new
- Migrated to TS
- All methods feature full JSDoc documentation
- Add new APIs with Promise and other modern JS features
- Test have been updated to work with the new APIs too
- Updated ESLint config that also does code formatting

# Why
I have used this project before, but only browser based, where the current stack was good enough, but now that I am using this project for a web-app with a bundler, where I like to use NPM packages, it simply wasn't enough any more.

2024-06-28 11:33 UTC, simplePCBuilding commented
Alright, I have finished this. I haven't bothered implementing tests for the new APIs, as they are the same as the old ones, but simply using modern browser APIs.

2024-06-28 11:34 UTC, simplePCBuilding commented
@lokesh Sorry for the large PR. It's a lot of changes in the package-lock.json and the built files

2024-06-28 12:10 UTC, simplePCBuilding commented
I would also like to suggest adding the wiki feature of GitHub. You can let me know when it is up, I can edit the Wiki for you and create docs. Alternatively, I could write some docs as a website

2024-08-26 06:18 UTC, simplePCBuilding commented
I might just publish my own version of this to npm, so both versions exist

2024-09-01 12:38 UTC, janishutz commented
I did publish my own package. `npm i @janishutz/color-thief`

2024-09-11 21:10 UTC, challet commented
> I did publish my own package. `npm i @janishutz/color-thief`

Your package is actually `@janishutz/colorthief` ;)

2024-09-12 04:15 UTC, janishutz commented
Ohh right... thanks for pointing this out!

2024-12-06 01:56 UTC, sillyangel requested changes
some of this is pointing to the wrong url's, and other data in package.json

2024-12-06 01:56 UTC, sillyangel commented on README.md
> +</div>
all of this is pointing to the wrong project

2024-12-06 01:56 UTC, sillyangel commented on README.md
> +```
linking to the wrong npm package

2024-12-06 01:56 UTC, sillyangel commented on package.json
> +    "name": "@janishutz/colorthief",
wrong package name, and version?

2024-12-06 01:56 UTC, sillyangel commented on package.json
> +        "name": "Janis Hutz",
wrong author data

2024-12-06 01:56 UTC, sillyangel commented on package.json
> +        "url": "https://github.com/janishutz/color-thief.git"
pointing to the wrong repository url

2024-12-06 06:27 UTC, janishutz commented
I should probably close this PR, running my own package with these features, as it seems that here the JS-only version will remain

2024-12-06 13:52 UTC, sillyangel commented
> I should probably close this PR, running my own package with these features, as it seems that here the JS-only version will remain

I agree

2024-12-09 10:48 UTC, closed without merging